from supabase import create_client

SUPABASE_URL = "https://qqzrfatsuqydxxjaailo.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxenJmYXRzdXF5ZHh4amFhaWxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQyODE4ODgsImV4cCI6MjA4OTg1Nzg4OH0.b8H7CGMthQd0lw7K6lyd4liCdgOUF2H1hDJzrbv4ODA"

supabase = create_client(SUPABASE_URL, SUPABASE_KEY)